os: unstable
image: Visual Studio 2015

platform:
  - x64

environment:
  matrix:
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"

before_build:
  - SET ARCH=x64
  - SET APP_PATH=%CD%
  - ps: $file = "$pwd\opencv.zip"
  - ps: (new-object System.Net.WebClient).Downloadfile("https://github.com/livecv/opencv_contrib/releases/download/3.4.0/opencv-contrib-3-4-0-msvc2015-x64-release.zip", $file)
  - ps: 7z x -y $file -o"."
  - ls
  - echo %CD%
  - SET OPENCV_DIR=%CD%\opencv\build\%ARCH%\vc14
  - SET QTDIR=C:\Qt\5.7\msvc2015_64
  - echo %OPENCV_DIR%

build_script:
  - cd build
  - echo %OPENCV_DIR%
  - echo %QTDIR%
  - ps: $file = "$pwd\deploy.zip"
  - ps: (new-object System.Net.WebClient).Downloadfile("https://github.com/livecv/live-pm/archive/master.zip", $file)
  - ps: 7z x -y $file -o"."
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - mv live-pm-master/* .
  - python --version
  - python livepm/main.py build .. msvc2015_64
  - python livepm/main.py deploy .. msvc2015_64
  - dir
